name: movie_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.3
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.6.0

dev_dependencies:
  auto_route_generator: ^5.0.1
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600

        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
